# Generated by Django 3.2.24 on 2024-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRound',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_link', models.CharField(max_length=45)),
                ('interview_link', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'test_round',
            },
        ),
    ]
