# Generated by Django 3.2.24 on 2024-04-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_round', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testround',
            options={'managed': False},
        ),
    ]
