# Generated by Django 3.2.16 on 2023-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('ap_id', models.AutoField(db_column='Ap_Id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
            ],
            options={
                'db_table': 'aptitude',
                'managed': False,
            },
        ),
    ]
