# Generated by Django 3.2.24 on 2024-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('skills', models.CharField(max_length=45)),
                ('compensation', models.IntegerField()),
                ('location', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('company_id', models.IntegerField()),
                ('post_time', models.TimeField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
