# Generated by Django 3.2.24 on 2024-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('department', models.CharField(max_length=45)),
                ('semester', models.CharField(max_length=45)),
                ('mail', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('cgpa', models.IntegerField()),
                ('skills', models.CharField(max_length=45)),
                ('certificates', models.CharField(max_length=45)),
                ('applied_jobs', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
