# Generated by Django 3.2.16 on 2023-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('cr_id', models.AutoField(db_column='Cr_Id', primary_key=True, serialize=False)),
                ('st_id', models.IntegerField(db_column='St_Id')),
                ('cl_id', models.IntegerField(db_column='Cl_Id')),
                ('prediction', models.CharField(db_column='Prediction', max_length=20)),
            ],
            options={
                'db_table': 'career',
                'managed': False,
            },
        ),
    ]
